---

- include: packages.yml

  # Read Jitsi Meet config files and extract secrets for use in template configs.
  # Import to run these tasks after package installation, but before config tasks.
- include: dynamic_vars.yml

- include: jitsi_meet.yml

- include: jicofo.yml

- include: prosody.yml

- include: sip_gateway.yml
  when: jitsi_meet_configure_sip_gateway  | bool

- include: videobridge.yml

- include: nginx.yml
  when: jitsi_meet_configure_nginx  | bool

- include: ufw.yml
  when: jitsi_meet_configure_firewall  | bool

- include: clean_up_default_configs.yml
  when: jitsi_meet_server_name != 'localhost'

  # Official recommended tweaks
- include: systemd.yml

- include: ui_customization.yml
  when: jitsi_meet_customize_the_ui | bool

  # Placing the browser extensions last so the associated debugging tasks
  # that display URLs are visible near the end of the play.
  # Build your own with https://github.com/jitsi/jidesha
- include: browser_extensions.yml
